version: '3'
services:
  app:
    build: ./app
    container_name: python_app
    depends_on:
      - db
    volumes:
      - ./app:/usr/src/app
    network_mode: "host"

  db:
    build: ./db
    container_name: sqlite_db
    volumes:
      - ./data:/data
    network_mode: "host"
